#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Library Version
VERSION_NAME=1.0.0

# Maven Central Publishing
GROUP=dev.onexeor
POM_ARTIFACT_ID=kdownloader
POM_NAME=KDownloader
POM_DESCRIPTION=Kotlin Multiplatform download manager for Android and iOS
POM_URL=https://github.com/OneXeor/KDownloader
POM_SCM_URL=https://github.com/OneXeor/KDownloader
POM_SCM_CONNECTION=scm:git:git://github.com/OneXeor/KDownloader.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/OneXeor/KDownloader.git
POM_LICENCE_NAME=Apache License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=onexeor
POM_DEVELOPER_NAME=Viktor Savchik