name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    environment: S
    name: Build & Publish
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Gradlew - Build & Publish
        env:
          USERNAME: ${{ secrets.USERNAME }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          ./gradlew build --no-daemon
          ./gradlew publish --no-daemon
