name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Gradlew - Build & Publish
        run: |
          ./gradlew build
          ./gradlew publish
